import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";

export const generateTelemediPrescriptionPdf = async ({ prescription, baseUrl }) => {
  // uploads/prescriptions folder
  const outDir = path.join(process.cwd(), "uploads", "prescriptions");
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

  const fileName = `telemedi_prescription_${prescription._id}.pdf`;
  const filePath = path.join(outDir, fileName);

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const stream = fs.createWriteStream(filePath);

    doc.on("error", reject);
    stream.on("finish", resolve);
    stream.on("error", reject);

    doc.pipe(stream);

    // Header
    doc.fontSize(18).text("TELEMEDICINE PRESCRIPTION", { align: "center" });
    doc.moveDown(1);

    doc.fontSize(12).text(`Patient Name: ${prescription.patientName}`);
    doc.text(`Age: ${prescription.age}`);
    doc.text(`Doctor: ${prescription.doctorName}`);
    doc.text(`Date: ${new Date(prescription.date).toLocaleDateString()}`);
    doc.moveDown(1);

    doc.fontSize(14).text("Medicines", { underline: true });
    doc.moveDown(0.5);

    if (!prescription.medicines?.length) {
      doc.fontSize(12).text("No medicines added.");
    } else {
      prescription.medicines.forEach((m, idx) => {
        doc.fontSize(12).text(`${idx + 1}. ${m.name}`);
        doc.fontSize(11).text(`   Dosage: ${m.dosage}`);
        doc.fontSize(11).text(`   Frequency: ${m.frequency}`);
        doc.moveDown(0.3);
      });
    }

    doc.moveDown(2);
    doc.fontSize(10).text("Generated by LukSuwa Telemedicine Module", { align: "center" });

    doc.end();
  });

  // public url
  const pdfUrl = `${baseUrl}/uploads/prescriptions/${fileName}`;
  return { pdfUrl, filePath, fileName };
};